export default {

  POST_POSTAUTHENDICATION_REQUEST: 'POST_POSTAUTHENDICATION_REQUEST',
  POST_POSTAUTHENDICATION_SUCCESS: 'POST_POSTAUTHENDICATION_SUCCESS',
  POST_POSTAUTHENDICATION_FAILURE: 'POST_POSTAUTHENDICATION_FAILURE',
  POST_POSTAUTHENDICATION_FAILURE_INVALID: 'POST_POSTAUTHENDICATION_FAILURE_INVALID',

  ODOO_CALL_REQUEST: 'ODOO_CALL_REQUEST',
  ODOO_CALL_SUCCESS: 'ODOO_CALL_SUCCESS',
  ODOO_CALL_FAILURE: 'ODOO_CALL_FAILURE',

  ADD_NOTIFICATION : "ADD_NOTIFICATION",


  CLEAR_SOPRODUCTS: "CLEAR_SOPRODUCTS",
  CLEAR_SONUMBERDETAIL: "CLEAR_SONUMBERDETAIL",

  CLEAR_LOGIN_FIELDS: 'CLEAR_LOGIN_FIELDS',
}