export default {

  POST_POSTAUTHENDICATION_REQUEST: 'POST_POSTAUTHENDICATION_REQUEST',
  POST_POSTAUTHENDICATION_SUCCESS: 'POST_POSTAUTHENDICATION_SUCCESS',
  POST_POSTAUTHENDICATION_FAILURE: 'POST_POSTAUTHENDICATION_FAILURE',
  POST_POSTAUTHENDICATION_FAILURE_INVALID: 'POST_POSTAUTHENDICATION_FAILURE_INVALID',

  POST_POSTMOBILEAUTH_REQUEST: 'POST_POSTMOBILEAUTH_REQUEST',
  POST_POSTMOBILEAUTH_SUCCESS: 'POST_POSTMOBILEAUTH_SUCCESS',
  POST_POSTMOBILEAUTH_FAILURE: 'POST_POSTMOBILEAUTH_FAILURE',
  POST_POSTMOBILEAUTH_FAILURE_INVALID: 'POST_POSTMOBILEAUTH_FAILURE_INVALID',
  POST_POSTMOBILEAUTH_RESET:'POST_POSTMOBILEAUTH_RESET',

  SEND_OTP_REQUEST: 'SEND_OTP_REQUEST',
  SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'SEND_OTP_FAILURE',
  SEND_OTP_RESET :'SEND_OTP_RESET ',

  VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
  VERIFY_OTP_FAILURE_INVALID: "VERIFY_OTP_FAILURE_INVALID",
  CLEAR_VERIFY_OTP : "CLEAR_VERIFY_OTP",

  POST_CREATEVISIT_REQUEST: "POST_CREATEVISIT_REQUEST",
  POST_CREATEVISIT_SUCCESS: "POST_CREATEVISIT_SUCCESS",
  POST_CREATEVISIT_FAILURE: "POST_CREATEVISIT_FAILURE",
  POST_CREATEVISIT_FAILURE_INVALID: "POST_CREATEVISIT_FAILURE_INVALID",

  POST_CUSTOMERLIST_REQUEST: "POST_CUSTOMERLIST_REQUEST",
  POST_CUSTOMERLIST_SUCCESS: "POST_CUSTOMERLIST_SUCCESS",
  POST_CUSTOMERLIST_FAILURE: "POST_CUSTOMERLIST_FAILURE",
  POST_CUSTOMERLIST_FAILURE_INVALID: "POST_CUSTOMERLIST_FAILURE_INVALID",

  POST_OUTSTANDING_REQUEST: "POST_OUTSTANDING_REQUEST",
  POST_OUTSTANDING_SUCCESS: "POST_OUTSTANDING_SUCCESS",
  POST_OUTSTANDING_FAILURE: "POST_OUTSTANDING_FAILURE",
  POST_OUTSTANDING_FAILURE_INVALID: "POST_OUTSTANDING_FAILURE_INVALID",

  POST_NEWVISIT_REQUEST: "POST_NEWVISIT_REQUEST",
  POST_NEWVISIT_SUCCESS: "POST_NEWVISIT_SUCCESS",
  POST_NEWVISIT_FAILURE: "POST_NEWVISIT_FAILURE",
  POST_NEWVISIT_FAILURE_INVALID: "POST_NEWVISIT_FAILURE_INVALID",

  POST_ACCESSREAD_REQUEST: "POST_ACCESSREAD_REQUEST",
  POST_ACCESSREAD_SUCCESS: "POST_ACCESSREAD_SUCCESS",
  POST_ACCESSREAD_FAILURE: "POST_ACCESSREAD_FAILURE",
  POST_ACCESSREAD_FAILURE_INVALID: "POST_ACCESSREAD_FAILURE_INVALID",

  POST_CONVERT_REQUEST: "POST_CONVERT_REQUEST",
  POST_CONVERT_SUCCESS: "POST_CONVERT_SUCCESS",
  POST_CONVERT_FAILURE: "POST_CONVERT_FAILURE",
  POST_CONVERT_FAILURE_INVALID: "POST_CONVERT_FAILURE_INVALID",


  ODOO_CALL_REQUEST: 'ODOO_CALL_REQUEST',
  ODOO_CALL_SUCCESS: 'ODOO_CALL_SUCCESS',
  ODOO_CALL_FAILURE: 'ODOO_CALL_FAILURE',

  ADD_NOTIFICATION : "ADD_NOTIFICATION",


  CLEAR_SOPRODUCTS: "CLEAR_SOPRODUCTS",
  CLEAR_SONUMBERDETAIL: "CLEAR_SONUMBERDETAIL",

  CLEAR_LOGIN_FIELDS: 'CLEAR_LOGIN_FIELDS',
}